name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY: tienda-frontend
  ECS_CLUSTER: tienda-perritos-cluster
  ECS_SERVICE: tienda-perritos-frontend-service
  CONTAINER_NAME: frontend

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Definir TAG de la imagen
      id: vars
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build imagen Docker frontend
      working-directory: ./frontend
      run: |
        docker build -t $ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }} .

    - name: Tag de la imagen con URL de ECR
      run: |
        ECR_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        docker tag $ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }} \
          $ECR_URL/$ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }}

    - name: Push de la imagen a ECR
      run: |
        ECR_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        docker push $ECR_URL/$ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }}

    - name: Descargar task definition base
      run: |
        aws ecs describe-task-definition \
          --task-definition tienda-perritos-frontend-task \
          --query taskDefinition > task-definition.json

    - name: Actualizar imagen en task definition
      id: taskdef
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.IMAGE_TAG }}

    - name: Deploy en ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.taskdef.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
